### ISSUE TITLE
Installation on Ubuntu

### ISSUE THREAD

**Issue by einarG-1qbit** [at2005/HODL#3]
Hello,
This project looks very interesting. However, there are no detailed instruction on how to install it on Ubuntu systems without Conda. Could you update the README file with more precise installation instructions.

It is also not clear what is meant by "To run the compiler, specify the --target system (qir/qasm) and the output file (-o)." I'm not a programmer, so detailed instructions would be appreciated.

**Comment by at2005** [comment]
I have updated the Readme with detailed instructions which I hope a non-programmer may be able to follow without much trouble. Let me know if any problem arises during installation.
