### ISSUE TITLE
Inconsistent results

### ISSUE THREAD

**Issue by einarG-1qbit** [at2005/HODL#5]
Hello,
The histogram from the demo jupyter notebook is not consistent with what is actually produced:
![sample img](https://user-images.githubusercontent.com/76973672/201242205-36f31dc7-bc19-421a-9cde-056b32b66371.png)

Instead of two bars in the histogram, I get one bar.

**Comment by at2005** [comment]
Hi,
The legacy modules code has been removed. I would refer you to the Python package (hodl-qiskit), the usage of which is described in the following tutorial: https://medium.com/@atamb/writing-qiskit-oracles-with-hodl-377859287861

**Comment by at2005** [comment]
Hi, could you confirm whether you are still getting this error please?
